import { TIssueItem } from "../types/issue.item.type";

export const dummyIssuesById: TIssueItem[] = [
  {
    id: "1",
    text: "انتهاك لحقوق الإنسان في مكان عام.",
    type: "violation",
    location: {
      lat: 33.5102,
      lng: 36.2913,
      governorate: "دمشق",
      city: "دمشق القديمة",
    },

    status: "open",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-14T21:00:00Z").toISOString(),
  },
  {
    id: "2",
    text: "وجود فساد مالي في إحدى الدوائر الحكومية.",
    type: "corruption",
    location: {
      lat: 35.5208,
      lng: 35.7917,
      governorate: "اللاذقية",
      city: "جبلة",
    },

    status: "inProgress",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-15T10:15:00Z").toISOString(),
  },
  {
    id: "3",
    text: "انقطاع دائم للكهرباء في المنطقة.",
    type: "serviceIssue",
    location: {
      lat: 32.6186,
      lng: 36.1028,
      governorate: "درعا",
      city: "نوى",
    },
    status: "resolved",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-03T12:30:00Z").toISOString(),
  },
  {
    id: "4",
    text: "اقتراح بإنشاء حديقة عامة جديدة.",
    type: "suggestion",
    location: {
      lat: 34.8049,
      lng: 38.0333,
      governorate: "حمص",
      city: "تلكلخ",
    },
    status: "open",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-04T14:45:00Z").toISOString(),
  },
  {
    id: "5",
    text: "وجود تعديات على الأملاك العامة في المنطقة.",
    type: "violation",
    location: {
      lat: 36.1998,
      lng: 37.1343,
      governorate: "حلب",
      city: "منبج",
    },
    status: "inProgress",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-05T16:00:00Z").toISOString(),
  },
  {
    id: "6",
    text: "الإبلاغ عن موظف يتلقى رشاوى.",
    type: "corruption",
    location: {
      lat: 35.0031,
      lng: 37.8285,
      governorate: "حماة",
      city: "السقيلبية",
    },
    status: "resolved",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-06T18:15:00Z").toISOString(),
  },
  {
    id: "7",
    text: "خلل في توزيع المياه في الأحياء.",
    type: "serviceIssue",
    location: {
      lat: 35.9476,
      lng: 39.0096,
      governorate: "دير الزور",
      city: "البوكمال",
    },
    status: "open",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-07T20:30:00Z").toISOString(),
  },
  {
    id: "8",
    text: "اقتراح لإصلاح الطرق الرئيسية في المدينة.",
    type: "suggestion",
    location: {
      lat: 35.5704,
      lng: 36.2619,
      governorate: "إدلب",
      city: "معرة النعمان",
    },
    status: "inProgress",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-08T22:45:00Z").toISOString(),
  },
  {
    id: "9",
    text: "احتكار في سوق الخضار يتسبب في ارتفاع الأسعار.",
    type: "corruption",
    location: {
      lat: 33.3152,
      lng: 36.8736,
      governorate: "ريف دمشق",
      city: "جرمانا",
    },
    status: "open",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-09T06:00:00Z").toISOString(),
  },
  {
    id: "10",
    text: "تعديات على الأراضي الزراعية في المنطقة.",
    type: "violation",
    location: {
      lat: 36.8065,
      lng: 41.1142,
      governorate: "الحسكة",
      city: "القامشلي",
    },
    status: "resolved",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-10T08:15:00Z").toISOString(),
  },
  {
    id: "11",
    text: "تأخير دائم في تقديم خدمات الصحة العامة.",
    type: "serviceIssue",
    location: {
      lat: 36.6111,
      lng: 37.3576,
      governorate: "الرقة",
      city: "الطبقة",
    },
    status: "open",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-11T10:30:00Z").toISOString(),
  },
  {
    id: "12",
    text: "اقتراح ببناء مكتبة عامة جديدة.",
    type: "suggestion",
    location: {
      lat: 36.065,
      lng: 37.3711,
      governorate: "حلب",
      city: "عفرين",
    },
    status: "resolved",
    files: [
      "https://picsum.photos/200/400/?blur",
      "https://picsum.photos/400/400/?blur",
      "https://picsum.photos/200/300/?blur",
    ],
    createdAt: new Date("2025-01-12T12:45:00Z").toISOString(),
  },
];
